/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./index.js]{@link ./index.js}
 * 
 **/
import { fileURLToPath } from "url";
import { dirname } from "path";
const __dirname = dirname(fileURLToPath(import.meta.url));
import { spawn }  from "child_process";
import { retro }  from "./node_modules/gradient-string/index.mjs";


const child = spawn("node", ["main.js"], {
  stdio: "pipe",
  shell: true,
  cwd: __dirname
});
child.stdout.on('data', (data) => {
  const retroOutput = retro(data.toString());
  process.stdout.write(retroOutput);
});

child.on('error', (err) => {
  console.error(`Error: ${err.message}`);
});

child.on('exit', (code) => {
  console.log(`Child process exited with code ${code}`);
});
