#!/usr/bin/env node
/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./FCA-TEMP/src/addExternalModule.js]{@link ./FCA-TEMP/src/addExternalModule.js}
 * 
 **/
import utils  from "../utils.mjs";
"use strict";



export default function (defaultFuncs, api, ctx) {
	return function addExternalModule(moduleObj) {
		if (utils.getType(moduleObj) == "Object") {
			for (const apiName in moduleObj) {
				if (utils.getType(moduleObj[apiName]) == "Function") {
					api[apiName] = moduleObj[apiName](defaultFuncs, api, ctx);
				} else {
					throw new Error(`Item "${apiName}" in moduleObj must be a function, not ${utils.getType(moduleObj[apiName])}!`);
				}
			}
		} else {
			throw new Error(`moduleObj must be an object, not ${utils.getType(moduleObj)}!`);
		}
	};
};
