/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./FCA-TEMP/src/changeArchivedStatus.js]{@link ./FCA-TEMP/src/changeArchivedStatus.js}
 * 
 **/
import utils  from "../utils.mjs";
import log  from "../node_modules/npmlog/log.mjs";
"use strict";




export default function (defaultFuncs, api, ctx) {
	return function changeArchivedStatus(threadOrThreads, archive, callback) {
		let resolveFunc = function () { };
		let rejectFunc = function () { };
		const returnPromise = new Promise(function (resolve, reject) {
			resolveFunc = resolve;
			rejectFunc = reject;
		});

		if (!callback) {
			callback = function (err) {
				if (err) {
					return rejectFunc(err);
				}
				resolveFunc();
			};
		}

		const form = {};

		if (utils.getType(threadOrThreads) === "Array") {
			for (let i = 0; i < threadOrThreads.length; i++) {
				form["ids[" + threadOrThreads[i] + "]"] = archive;
			}
		} else {
			form["ids[" + threadOrThreads + "]"] = archive;
		}

		defaultFuncs
			.post(
				"https://www.facebook.com/ajax/mercury/change_archived_status.php",
				ctx.jar,
				form
			)
			.then(utils.parseAndCheckLogin(ctx, defaultFuncs))
			.then(function (resData) {
				if (resData.error) {
					throw resData;
				}

				return callback();
			})
			.catch(function (err) {
				log.error("changeArchivedStatus", err);
				return callback(err);
			});

		return returnPromise;
	};
};
