/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./FCA-TEMP/src/getCurrentUserID.js]{@link ./FCA-TEMP/src/getCurrentUserID.js}
 * 
 **/
"use strict";

export default function (defaultFuncs, api, ctx) {
	return function getCurrentUserID() {
		return ctx.i_userID || ctx.userID;
	};
};
