/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./FCA-TEMP/src/handleMessageRequest.js]{@link ./FCA-TEMP/src/handleMessageRequest.js}
 * 
 **/
import utils  from "../utils.mjs";
import log  from "../node_modules/npmlog/log.mjs";
"use strict";




export default function (defaultFuncs, api, ctx) {
	return function handleMessageRequest(threadID, accept, callback) {
		if (utils.getType(accept) !== "Boolean") {
			throw {
				error: "Please pass a boolean as a second argument."
			};
		}

		let resolveFunc = function () { };
		let rejectFunc = function () { };
		const returnPromise = new Promise(function (resolve, reject) {
			resolveFunc = resolve;
			rejectFunc = reject;
		});

		if (!callback) {
			callback = function (err, friendList) {
				if (err) {
					return rejectFunc(err);
				}
				resolveFunc(friendList);
			};
		}

		const form = {
			client: "mercury"
		};

		if (utils.getType(threadID) !== "Array") {
			threadID = [threadID];
		}

		const messageBox = accept ? "inbox" : "other";

		for (let i = 0; i < threadID.length; i++) {
			form[messageBox + "[" + i + "]"] = threadID[i];
		}

		defaultFuncs
			.post(
				"https://www.facebook.com/ajax/mercury/move_thread.php",
				ctx.jar,
				form
			)
			.then(utils.parseAndCheckLogin(ctx, defaultFuncs))
			.then(function (resData) {
				if (resData.error) {
					throw resData;
				}

				return callback();
			})
			.catch(function (err) {
				log.error("handleMessageRequest", err);
				return callback(err);
			});

		return returnPromise;
	};
};
